[package]
name = "docker-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
filedesc = "0.5.0"